
import "~/styles/globals.css";

import { type Metadata } from "next";
import { cn } from "~/lib/utils";
import { fontSans} from "~/lib/fonts";
import { ThemeProvider } from "~/components/providers";
import { TRPCReactProvider } from "~/trpc/react";
import ChatSupport from "~/components/chat-support";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
        )}>
        <TRPCReactProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
        </TRPCReactProvider>
        <ChatSupport />
        </body>
        </html>
    );
}